### ISSUE TITLE
Remove/hide one of the categories

### ISSUE THREAD

**Issue by webmastir** [leandrosa81/taskbar-monitor#13]
Maybe I'm missing it _(assuming it's possible)_, but is there a way to remove "DISK" or "MEM" from the taskbar?

**Comment by KoalaBear84** [comment]
If you have one of the latest versions you can do the following:
1. Right click the taskbar-monitor deskband
2. Click settings...
![image](https://user-images.githubusercontent.com/5886900/111496206-652c7080-8740-11eb-8a26-b30a4d3c66f4.png)
3. Go to GRAPHS section
4. Disable the parts you want
![image](https://user-images.githubusercontent.com/5886900/111496309-7f664e80-8740-11eb-9dd7-6c166852d4c1.png)
