### ISSUE TITLE
cant find files

### ISSUE THREAD

**Issue by derpieler** [leandrosa81/taskbar-monitor#17]
Hi,

I can't find the TaskbarMonitorInstaller.exe file oder TaskbarMonitor.dll as described in the install.txt oder readme.md

What am i doing wrong?

best regards
christian

**Comment by leandrosa81** [comment]
Hi, @derpieler 

You will find the latest installer here: https://github.com/leandrosa81/taskbar-monitor/releases/latest

Just download the file and execute it, it will install the taskbar-monitor on your computer. 
If the program does not appear on the taskbar right away, you must click on the taskbar with the right mouse button and select "taskbar-monitor" inside the "Toolbars" menu.

**Comment by derpieler** [comment]
yes that works. Many thanks
