### ISSUE TITLE
Error while starting / initializing (SetCompatibleTextRenderingDefault)

### ISSUE THREAD

**Issue by KoalaBear84** [leandrosa81/taskbar-monitor#19]
I've not been able to use taskbar-monitor for over a month now. Finally added error handling and found out the problem. Added a PR for the error handling too: #18 

This is the error. Not sure if this was added in one of the latest releases.

---------------------------
Microsoft® Windows® Operating System
---------------------------
SetCompatibleTextRenderingDefault must be called before the first IWin32Window object is created in the application.
---------------------------
OK   
---------------------------

![image](https://user-images.githubusercontent.com/5886900/121341286-ccf9ee00-c920-11eb-9eeb-2e1fd7c85c41.png)

**Comment by leandrosa81** [comment]
just released new version that should address this, thank you for reporting.

**Comment by KoalaBear84** [comment]
It works. Looks like you forgot to update the version number, so I thought updating didn't work, but it works, so it did. And don't see version number changes. Se we need #15 to prevent it 😂
