### ISSUE TITLE
Text font stucked to bold.

### ISSUE THREAD

**Issue by logan2k** [leandrosa81/taskbar-monitor#21]
No matter which font you choose, the style will always be fixed to bold, even if you select other style and apply it, the final results are always bold style.

**Comment by KoalaBear84** [comment]
Without any screenshots, with some examples?

**Comment by logan2k** [comment]
> 
> 
> Some screenshots would be nice so it can be seen. Please add a screenshot of the font dialog as well.

![1](https://user-images.githubusercontent.com/79699834/121885165-5a638680-cd03-11eb-95d8-5de2fc8eb545.PNG)

**Comment by KoalaBear84** [comment]
Please see the posted screenshot, "Bold" is selected, please select "Regular":
![image](https://user-images.githubusercontent.com/5886900/121885749-d6b29580-cd14-11eb-8163-886fd8d9f43d.png)

**Comment by logan2k** [comment]
![1](https://user-images.githubusercontent.com/79699834/121886215-af53cc80-cd04-11eb-8fd8-57fa9e949d17.PNG)

**Comment by KoalaBear84** [comment]
What happens when you press "OK" after this, and "Apply" after that?

**Comment by logan2k** [comment]
> 
> 
> What happens when you press "OK" after this, and "Apply" after that?

No need to apply to see the bug.
After press OK, the style is just ignored, you can see the preview is still bold, and you can immediately click the font setting and see it's reset to bold.

**Comment by KoalaBear84** [comment]
Sorry for not believing you. I see this is hardcoded. Then we'll wait for @leandrosa81 to answer.

See for code:
https://github.com/leandrosa81/taskbar-monitor/blob/master/TaskbarMonitor/OptionForm.cs#L118

**Comment by leandrosa81** [comment]
now you should be able to change font style too, let me know if there is any problem.

**Comment by KoalaBear84** [comment]
Hmm, looks like I cannot get it to Bold now, the rest sometimes works.

Top is old, bottom is new.
![image](https://user-images.githubusercontent.com/5886900/121993865-85ea7d80-cda4-11eb-8115-7391337e38f0.png)
