### ISSUE TITLE
Cannot toggle off and on in the same user session

### ISSUE THREAD

**Issue by logan2k** [leandrosa81/taskbar-monitor#22]
If right click taskbar, then go to "toolbars" and disable taskbar-monitor, you cannot turn it back on, until you log off your windows user, and login back again.

**Comment by KoalaBear84** [comment]
This might be the same issue as #19

We cannot tell until the error handling (#18) is in a new release.

**Comment by leandrosa81** [comment]
just released new version that should address this, thank you for reporting.
