### ISSUE TITLE
CPU meter accuracy?

### ISSUE THREAD

**Issue by MM102** [leandrosa81/taskbar-monitor#24]
![cpu](https://user-images.githubusercontent.com/9996046/126694589-10192dc6-3375-4738-84ca-150c70b68c2e.PNG)

I understand that acurately tracking cpu usage is hard/impossible, but I was wondering if you knew why there was such a big discrepancy between this and other apps.
More importantly the discrepancy between the percent shown and the bar graph behind it.

Processor information:
Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, 2592 Mhz, 6 Core(s), 12 Logical Processor(s)

**Comment by KoalaBear84** [comment]
It is not easy indeed. Also depends on the interval of the polling of the data.

But I do see that there is a difference in it. Never really checked it out.

**Comment by leandrosa81** [comment]
I will investigate this issue, maybe it has something to do with issue #20 .  Here it seems fine (eg: CPU at 19%):
![image](https://user-images.githubusercontent.com/143780/126987140-c03cd40c-5f41-4107-b906-9e0702e494ba.png)
laptop specs: Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz   2.11 GHz, 4 Core(s), 8 Logical Processor(s)

**Comment by 70legne** [comment]
Maybe the bar just shows a single cpu?

<img width="281" alt="Taskbar-cpu-1" src="https://user-images.githubusercontent.com/89074155/129704428-b1e6e2e9-04e5-4e3f-9011-48be2f98fd6f.PNG">

**Comment by leandrosa81** [comment]
I am working on this issue, should be fixed on the next release.

**Comment by jherrera123** [comment]
You might already have seen this post: https://stackoverflow.com/a/63732722

The author of this answer mentions you should use Processor Information/%Processor Utility/_Total to match the task manager.

```csharp
 cpuCounter = new PerformanceCounter(
            "Processor Information",
            "% Processor Utility",
            "_Total",
            true
        );
```
