### ISSUE TITLE
how to enter settings

### ISSUE THREAD

**Issue by OrenNisa** [leandrosa81/taskbar-monitor#26]
accidentally I disable all graghs and I can't go to setting to enable it. what can I do?

**Comment by leandrosa81** [comment]
Sorry to hear that, you can manually enable at least a single graph, by editing the config file in C:\Users\<USER>\AppData\Local\Programs\taskbar-monitor\config.json (remove from the taskbar before editing, then put it back after saving the file).

**Comment by OrenNisa** [comment]
> 
> 
> Sorry to hear that, you can manually enable at least a single graph, by editing the config file in C:\Users<USER>\AppData\Local\Programs\taskbar-monitor\config.json (remove from the taskbar before editing, then put it back after saving the file).

thank you!

**Comment by OrenNisa** [comment]
> 
> 
> Sorry to hear that, you can manually enable at least a single graph, by editing the config file in C:\Users<USER>\AppData\Local\Programs\taskbar-monitor\config.json (remove from the taskbar before editing, then put it back after saving the file).

thank you!
