### ISSUE TITLE
Windows 11 Support

### ISSUE THREAD

**Issue by hofq** [leandrosa81/taskbar-monitor#29]
Hey there,

it would be cool if the Taskbar Monitor could Support Windows 11.

Thanks for your Work :)

**Comment by leandrosa81** [comment]
Hey, On Windows 11 we don't have deskbands anymore on the taskbar, where this monitor used to reside. 
I have been working on a minimum windows 11-compatible version using a different approach, but got a few issues yet to solve (related to mouse events and some cleanup after exiting the app).
As soon as I clear these bugs, I will release it here.

**Comment by freeflyer454** [comment]
Dang.  I just updated my laptop a few hours ago to Win11... Disappointed to learn I can no longer have taskbar-monitor.  It's been one of my must-have apps.  I want to thank you for making such a handy program and working on it's replacement.  I hope the replacement is still progressing.
