### ISSUE TITLE
How do I uninstall?

### ISSUE THREAD

**Issue by Actii** [leandrosa81/taskbar-monitor#3]
Hi there,
How do I completely remove the taskbar-monitor from my computer. I can make it disappear but I don' see any option to completely uninstall it. (I want to keep it on my work computer not in personal)

![image](https://user-images.githubusercontent.com/13372586/110239143-6fc75880-7f3d-11eb-873d-a9146f7bd1b2.png)

**Comment by leandrosa81** [comment]
Hi, if you used the installer (the new version) you can run the same installer with the "/uninstall" option, or manually unregister the dll with the following commands:

64bit:
%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\regasm.exe /unregister "TaskbarMonitor.dll"
32bit:
%SystemRoot%\Microsoft.NET\Framework\v4.0.30319\regasm.exe /unregister "TaskbarMonitor.dll"

Hope it helps. Still working to get correctly registered in the programs listing, so you can easily uninstall from there. Sorry for that.

**Comment by Actii** [comment]
Thanks, it worked.

**Comment by enterv0id** [comment]
Hey, I tried to remove it with:
`%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\regasm.exe /unregister "TaskbarMonitor.dll"`

but it throws the error:
`RegAsm : error RA0000 : Unable to locate input assembly 'TaskbarMonitor.dll' or one of its dependencies.`

Win 10 - 64bit 22H2
