### ISSUE TITLE
The Value Between Taskbar Monitor and Real Condition is Different

### ISSUE THREAD

**Issue by Coffeelatte369** [leandrosa81/taskbar-monitor#37]
Hey, i just wanna know is it normal or is it a bug that the CPU value that it shows is different comparing to what i saw in task manager, also it's different comparing to the resource monitor (when i right click the taskbar monitor).

<img width="94" alt="Screenshot 2022-08-20 004559" src="https://user-images.githubusercontent.com/111590878/185667644-053302e0-12e5-4379-bb3b-c97b67802a1d.png">

Down there is what it shows on my taskbar and up there is what resource monitor shows me (it has same value comparing to task manager), i also noticed the value on my taskbar show is kinda halved, so if my cpu works on 30% in my task manager, the one in taskbar will show 15% to me. 

My setting:
![takbar-monitor_ settings 20-Aug-22 12_49_04 AM](https://user-images.githubusercontent.com/111590878/185668271-991cb21c-3315-4a9f-bca5-fcd9895a9a53.png)

**Comment by KoalaBear84** [comment]
I do experience the same issue, sometimes with a big difference. And it isn't the timing.

**Comment by leandrosa81** [comment]
Please, let me know if this problem goes away with the new v0.4.0 version.
