### ISSUE TITLE
Add option to disable stuff you don't use

### ISSUE THREAD

**Issue by thewan056** [leandrosa81/taskbar-monitor#4]
Cool system monitor. Definitely prefer this style of presentation instead of text based only from other taskbar system monitors. 

Would like suggest an option to disable/hide what you don't use. I don't really need the disk read write info, so I would prefer to hide that to reduce clutter on my taskbar. Not sure if this was part of your roadmap since it wasn't specifically mentioned.

BTW i found your monitor via [ghacks](https://www.ghacks.net/2021/03/07/taskbar-monitor-displays-a-deskband-to-indicate-your-computers-resource-usage/).

**Comment by KoalaBear84** [comment]
I'm not the author, just want to say that it's cool that it's mentioned somewhere 😀

**Comment by profucius** [comment]
Agreed, I would like to have the option to disable ones that I do not need, for instance I do not need Disk stats.

**Comment by leandrosa81** [comment]
I did not think of that, but definitely will add on the next version, should be simple to do so.

**Comment by leandrosa81** [comment]
published new version (0.3.2) with support for disabling a specific graph if you want. let me know if it works for you.

**Comment by profucius** [comment]
This worked for me, I was able to disable Disk as I do not use it.

**Comment by thewan056** [comment]
something seems broken with the latest version 0.3.2. Upon running the installer my explorer crashes and windows stops responding, so i can't test this yet

**Comment by profucius** [comment]
@thewan056  since you got it working, can you verify if you are experiencing #8 as well?
