### ISSUE TITLE
CPU usage is 121%

### ISSUE THREAD

**Issue by bediicco** [leandrosa81/taskbar-monitor#43]
Hey, i love this tool!

Please update it to 1.0 :-)

I have an error with my Xeon E5 2695V3 (14/28C). It shows 121% CPU usage. I do not know when it begins to spread. 3% in Task-Manager is 3% in tbm. But than, it goes up to around 121%...

![image](https://user-images.githubusercontent.com/126161988/221681747-5276864f-8944-47b8-98dc-fa6973b7bd6d.png)

**Comment by leandrosa81** [comment]
Hello, I am glad you find this tool useful. 
This behavior is from Windows itself, I think when Intel Turbo Boost is enabled the performance counter exceeds 100%. 
It is the same Performance Counter utilized by the Windows Task Manager, but I think it truncates the value to a maximum of 100%. I will add an option to do the same in the near future, but I think some people would like to get some feedback when Turbo Boost is enabled, so this is what I am thinking about adding on the options:

- Add option to limit the value at a maximum value of 100%; 
- Add option to show additional boost value (e.g. something like "100% +21");
- Add option to display like 121%.

Please, let me know what you guys think about this.

**Comment by bediicco** [comment]
I just give a thumb up, but thats more about explaining it to me. Thank you 👍 

Personally for me 100% is ok, i do not need a boost value.
