### ISSUE TITLE
Color glitch

### ISSUE THREAD

**Issue by vncastanheira** [leandrosa81/taskbar-monitor#5]
https://user-images.githubusercontent.com/1210284/110261071-71207180-7f8d-11eb-9ced-67ca6c9a2b1a.mp4

Got the color letters appearing very dark greyish and then suddenly getting white when you hover over them. Is this intended?

Using dark theme with Windows 10 20H2.

**Comment by KoalaBear84** [comment]
I know it is intentional, should be added to the readme so it is documented :)

**Comment by leandrosa81** [comment]
Yeah this hover behavior is intentional but in the next version you will be able to customize it and disable this effect.

**Comment by leandrosa81** [comment]
With the new version 0.3.2 you can change this behavior and disable the effect.
