### ISSUE TITLE
Taskbar startup error

### ISSUE THREAD

**Issue by MaryanHru** [leandrosa81/taskbar-monitor#53]
I installed the program, everything worked fine, but at some point it gives this error, how to fix?

Version: 1.0.0.0
Date: 31-Aug-24
Time: 14:10:15

Exception:
 Sequence contains no elements
Source:
 System.Core
Target site:
 Single
Stack trace:
    at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at TaskbarMonitor.TaskbarManager.GetOptionsForTaskbar(Taskbar tb)
   at TaskbarMonitor.TaskbarManager.AddControlToTaskbar(WindowInformation taskbarArea, WindowInformation trayArea, Boolean isMainTaskbar)
   at TaskbarMonitor.TaskbarManager.AddControlsToTaskbars()
   at TaskbarMonitorWindows11.Program.Main()
![1](https://github.com/user-attachments/assets/4c7103e8-0348-41b7-abd4-2d1088f4dd66)

**Comment by leandrosa81** [comment]
Hello, I think this issue is related to the multi-monitor support I have included in the last version. But sometimes windows decides to remove and add screens for no reason at all. I will soon release a new version that should fix this.

**Comment by MaryanHru** [comment]
> Hello, I think this issue is related to the multi-monitor support I have included in the last version. But sometimes windows decides to remove and add screens for no reason at all. I will soon release a new version that should fix this.

I had this happen after I turned off Intel Graphics, then it stopped working at all with the integrated video card turned off or on

**Comment by MaryanHru** [comment]
FIXED

Error when launching Taskbar Monitor due to incorrect display configuration (e.g., referencing DISPLAY5).
I open configuration in %appdata% and change \\\\.\\DISPLAY5 to \\\\.\\DISPLAY1.
