### ISSUE TITLE
Able to change the font size

### ISSUE THREAD

**Issue by profucius** [leandrosa81/taskbar-monitor#6]
Great taskbar addon. I would like to request the ability to increase/decrease the font size, for instance the CPU percentage.

I use a 55" screen at 4K resolution, and the default font size is small enough that I need to lean forward to read the text.

**Comment by leandrosa81** [comment]
Alright, will add this option to the next version. I plan to release it at the end of the week.

**Comment by leandrosa81** [comment]
published new version (0.3.2) with support for changing font family and size. let me know if it solves your problem.

**Comment by profucius** [comment]
Excellent, this is perfect. Thank you for incorporating this feature. I'll close this out now.
